sheinsight/shineout-next

.gitignore
jest.config.ts
packages/base/src/breadcrumb/breadcrumb.tsx
packages/base/src/modal/modal-content.tsx
packages/base/src/modal/use-modal-move.ts
packages/base/src/table/tr.tsx
packages/shineout/src/alert/__test__/__snapshots__/alert.spec.tsx.snap
packages/shineout/src/alert/__test__/alert.spec.tsx
packages/shineout/src/breadcrumb/__test__/__snapshots__/breadcrumb.spec.tsx.snap
packages/shineout/src/breadcrumb/__test__/breadcrumb.spec.tsx
packages/shineout/src/drawer/__test__/__snapshots__/drawer.spec.tsx.snap
packages/shineout/src/drawer/__test__/drawer.spec.tsx
packages/shineout/src/list/__test__/list.spec.tsx
packages/shineout/src/modal/__test__/__snapshots__/modalSnapshot.spec.tsx.snap
packages/shineout/src/modal/__test__/modal.spec.tsx
packages/shineout/src/modal/__test__/modalSnapshot.spec.tsx
packages/shineout/src/table/__example__/07-01-virtual-list.tsx
packages/shineout/src/table/__example__/18-01-tree.tsx
packages/shineout/src/table/__test__/__snapshots__/table.spec.tsx.snap
packages/shineout/src/table/__test__/table.spec.tsx
packages/shineout/src/tests/utils.tsx

Table test

---

packages/shineout/src/descriptions/__example__/05-arrangement.tsx

fix: repair example keygen

---

packages/hooks/src/components/use-table/use-table-sort.ts

fix: change menual to manual

---

package.json

feat: 3.3.0 beta.9

---

packages/shineout/src/tabs/interface.ts

add Tabs PanelProps type export

feat: 🎸 add Tabs PanelProps type export

---

packages/hooks/src/components/use-datepicker/use-datepicker-range.ts
packages/shineout/src/date-picker/__doc__/changelog.cn.md

fix: repair start time can more than the end time when set range is number

fix: repair date range question

---

docs/theme/components/style.ts
docs/theme/components/title/index.tsx
docs/theme/components/title/logo.tsx

feat: 更新文档样式

---

package.json

feat: 调整 3.0 为 latest

---

packages/base/src/card-group/index.ts
packages/shineout/src/card-group/index.ts

feat: 对外导出LazyLoad组件

---

package.json
packages/base/src/table/table.tsx
packages/hooks/src/components/use-table/use-table-layout.tsx
packages/hooks/src/components/use-table/use-table-virtual.tsx
packages/shineout/src/table/__doc__/changelog.cn.md
packages/shineout/src/table/__example__/test-006-fix-scroll-y.tsx

- 修复`Table`的虚拟列表场景下的合并行中内容闪烁的问题
- 修复`Table`的列中有动态加载的内容导致tbody和thead不对齐的问题

修复Table的虚拟列表场景下的合并行中内容闪烁的问题

---

packages/hooks/src/components/use-table/use-table-virtual.tsx
packages/shineout/src/table/__example__/test-006-fix-scroll-y.tsx

fix: Table虚拟滚动和合并行同时使用的问题

---

packages/base/src/cascader/cascader.type.ts
packages/base/src/tree-select/tree-select.type.ts

- style type: inputPlaceholder

fix: style type: inputPlaceholder

---

packages/shineout-style/src/cascader/cascader.ts
packages/shineout-style/src/tree-select/tree-select.ts
packages/shineout/src/cascader/__doc__/changelog.cn.md
packages/shineout/src/tree-select/__doc__/changelog.cn.md

- 修正Casecader和TreeSelect的inputPlaceholder样式

fix: 修正Casecader和TreeSelect的inputPlaceholder样式

---

package.json
packages/base/src/select/list.tsx
packages/base/src/select/select.tsx
packages/base/src/select/select.type.ts
packages/base/src/virtual-scroll/scroll.tsx
packages/base/src/virtual-scroll/virtual-scroll-list.tsx
packages/shineout-style/src/select/select.ts
packages/shineout/src/select/__doc__/changelog.cn.md
packages/shineout/src/select/__example__/01-01-base.tsx
packages/shineout/src/select/__example__/19-loadmore.tsx
packages/shineout/src/select/__example__/20-trigger.tsx

- 新增 `onLoadMore` 属性，支持滚动加载
- 新增 `threshold` 属性，支持设置滚动加载阈值
- 新增 `trigger` 属性，支持更改展开下拉面板的触发方式

feat: Select 新增滚动加载、更改触发打开面板方式功能

---

package.json
packages/base/src/date-picker/date-picker.type.ts
packages/base/src/date-picker/picker.tsx
packages/base/src/date-picker/quick.tsx
packages/base/src/date-picker/quick.type.ts
packages/hooks/src/components/use-datepicker/util.ts
packages/shineout-style/src/date-picker/date-picker.ts
packages/shineout/src/date-picker/__doc__/changelog.cn.md
packages/shineout/src/date-picker/__example__/09-quick.tsx
packages/theme/src/date-picker/date-picker.ts
packages/theme/src/date-picker/token.ts
packages/theme/src/date-picker/type.ts

- 修复 `Datepicker` 快速选择固定值无法高亮的问题

fix: 修复 Datepicker 快速选择固定值无法高亮的问题

---

packages/shineout/src/date-picker/__test__/datePicker.spec.tsx

chore: 修改DatePicker的测试用例

---

packages/shineout-style/src/normalize.ts

- 修正normalize.css，对齐shineout v1和v2

fix: 修正normalize.css

---

package.json
packages/base/src/checkbox/checkbox-group.tsx
packages/shineout/src/checkbox/__doc__/changelog.cn.md
packages/shineout/src/checkbox/__example__/test-001-group-onchange.tsx

- `Radio.Group` children onChange fix

fix: `Radio.Group` children onChange fix

---

docs/theme/layout/desktop/menu/index.tsx
docs/theme/layout/desktop/style.ts
packages/shineout/src/collapse/__doc__/index.md
packages/shineout/src/descriptions/__doc__/index.md
packages/shineout/src/empty/__doc__/index.md
packages/shineout/src/steps/__doc__/index.md

doc: 标记3.0新增的组件

---

package.json
packages/base/src/select/list-option.tsx
packages/base/src/select/list-option.type.ts
packages/base/src/select/list.tsx
packages/base/src/select/select.type.ts
packages/base/src/table/table.tsx
packages/base/src/table/table.type.ts
packages/base/src/virtual-scroll/virtual-scroll-list.tsx
packages/base/src/virtual-scroll/virtual-scroll-list.type.ts
packages/shineout-style/src/select/select.ts
packages/shineout/src/select/__doc__/changelog.cn.md
packages/shineout/src/select/__example__/04-bigdata.tsx
packages/shineout/src/select/__test__/__snapshots__/select.spec.tsx.snap
packages/shineout/src/transfer/__test__/__snapshots__/transfer.spec.tsx.snap

feat: Select 支持动态虚拟列表高度

---

docs/theme/components/example/index.tsx

feat: 调整文档操作按钮

---

packages/base/src/popover/popover.tsx
packages/shineout/src/popover/__doc__/changelog.cn.md

- 修复 `Popover` 组件 children 点击事件冒泡外层的问题

fix: 修复 Popover 组件 children 点击事件冒泡外层的问题

---

package.json
packages/hooks/src/common/use-input-able/use-Input-able.ts
packages/hooks/src/components/use-input/use-input-number.ts
packages/shineout/src/input/__doc__/changelog.cn.md
packages/shineout/src/input/__example__/t-14-invalid-number.tsx

- 修复`Input.Number` 输入过程中的字符串格式(例如1.)触发onChange的问题
- 修复`Input`的defaultValue初始化生效问题

Fix input number on change

---

package.json
packages/base/src/dropdown/dropdown.type.ts
packages/base/src/dropdown/dropdownIn.tsx
packages/shineout/src/dropdown/__doc__/changelog.cn.md

feat: `Dropdown` 组件新增 `zIndex` 属性

---

packages/hooks/src/components/use-datepicker/use-datepicker-format.ts
packages/shineout-style/src/version.ts
packages/shineout/src/index.ts

fix: datepicker ts type fix

---

package.json
packages/base/src/select/list-option.tsx
packages/base/src/select/list.tsx
packages/base/src/virtual-scroll/virtual-scroll-list.tsx
packages/base/src/virtual-scroll/virtual-scroll-list.type.ts
packages/hooks/src/components/use-table/use-table-virtual.tsx
packages/shineout/src/select/__doc__/changelog.cn.md

- 修复 Select 动态 lineHeight 过滤场景下滚动异常的问题

fix: 修复 Select 动态 lineHeight 过滤场景下滚动异常的问题

---

packages/base/src/date-picker/day.tsx
packages/shineout-style/src/date-picker/date-picker.ts

- `DatePicker`开启needConfirm后的样式微调

Fix datepicker needconfirm style/3.4.0

---

package.json
packages/shineout-style/src/rate/rate.ts
packages/shineout/src/rate/__doc__/changelog.cn.md

- 修复 `Rate` 组件在 Safari 浏览器下对齐样式异常的问题

fix: 修复 `Rate` 组件在 Safari 浏览器下对齐样式异常的问题

---

packages/base/src/tree-select/tree-select.tsx
packages/base/src/tree-select/tree-select.type.ts
packages/shineout/src/tree-select/__doc__/changelog.cn.md

- 修复 `TreeSelect` 组件 `filterDelay` 属性失效的问题

fix: 修复 `TreeSelect` 组件 `filterDelay` 属性失效的问题 

---

packages/base/src/textarea/textarea.tsx
packages/base/src/textarea/textarea.type.ts
packages/shineout-style/src/textarea/textarea.ts
packages/shineout/src/textarea/__doc__/changelog.cn.md

- `Textarea` 组件 `info` 属性新增配置模式，支持配置定位

feat: `Textarea` 组件 `info` 属性新增配置模式，支持配置定位

---

packages/base/src/table/table.tsx
packages/base/src/virtual-scroll/scroll.tsx
packages/shineout/src/table/__example__/test-006-table-scroll-y.tsx
packages/shineout/src/table/__example__/test-007-table-tabs.tsx
packages/shineout/src/transfer/__test__/__snapshots__/transfer.spec.tsx.snap

perf: `Table`虚拟表格初始化性能优化

---

README-zh_CN.md
README.md

chore: update readme

---

package.json
packages/base/src/tabs/tab.tsx
packages/base/src/tabs/tabs-header.tsx
packages/shineout/src/tabs/__example__/t-02-tabs-link2.tsx

- fix: 修复`Tabs.Panel`的tab属性设置为lcd的Link组件导致的报错问题2

fix: 修复`Tabs.Panel`的tab属性设置为lcd的Link组件导致的报错问题2

---

package.json
packages/hooks/src/components/use-tree/use-tree.ts
packages/shineout/src/tree/__doc__/changelog.cn.md

- 修复 useTree 在重复 key 数据情况下后续节点无法正常注册的问题

fix: 修复 useTree 在重复 key 数据情况下后续节点无法正常注册的问题

---

packages/base/src/tabs/tabs-header.tsx
packages/shineout/src/tabs/__example__/t-03-tabs-nest-line-style.tsx

fix: Tabs line样式

---

packages/hooks/src/common/use-list-select/use-list-select-multiple.ts
packages/hooks/src/common/use-list-select/use-list-select.ts
packages/hooks/src/common/use-list-select/use-list.type.ts

fix: 修复Select的onChange第2参的类型

---

packages/base/src/list/list.tsx
packages/hooks/src/common/use-list-select/use-list-select-multiple.ts
packages/hooks/src/common/use-list-select/use-list-select.ts
packages/hooks/src/common/use-list-select/use-list.type.ts
packages/hooks/src/components/use-select/use-select.ts
packages/shineout-style/src/version.ts
packages/shineout/src/index.ts
packages/shineout/src/transfer/__example__/09-control.tsx

fix: onChange回调参数类型

---

package.json
packages/shineout-style/src/message/message.ts
packages/shineout/src/message/__doc__/changelog.cn.md

fix: 修复 Message 样式生成异常的问题

---

package.json
packages/hooks/src/components/use-image/use-image.ts
packages/shineout/src/image/__doc__/changelog.cn.md

- 修复 `Image` 组件动态 src 场景下组件状态异常的问题

fix: 修复 `Image` 组件动态 src 场景下组件状态异常的问题

---

docs/theme/layout/desktop/menu/index.tsx

fix: 去除文档无效设置

---

packages/shineout/src/form/__example__/014-table.tsx

chore: add example of Form

---

package.json

chore: release-3.4.4-beta.1

---

package.json

chore: edit version

---

package.json

chore: version 3.4.4-beta.4

---

package.json
packages/base/src/input/input.tsx
packages/shineout/src/form/__doc__/changelog.cn.md

fix: 修复 `Input` 无法输入的问题

---

package.json
packages/base/src/date-picker/date-picker.tsx
packages/base/src/date-picker/date-picker.type.ts
packages/base/src/date-picker/picker.tsx
packages/base/src/date-picker/quick.tsx
packages/base/src/date-picker/quick.type.ts
packages/shineout/src/date-picker/__doc__/changelog.cn.md
packages/shineout/src/date-picker/__example__/09-quick.tsx

feat: `DatePicker` 快速选择支持立刻关闭面板功能

---

package.json
packages/base/src/pagination/pagination-size-list.tsx
packages/base/src/pagination/pagination-size-list.type.ts
packages/base/src/pagination/pagination.tsx
packages/base/src/pagination/pagination.type.ts
packages/shineout/src/pagination/__doc__/changelog.cn.md

- `Pagination` 新增 `select` 属性支持配置弹窗部分信息

feat: `Pagination` 新增 `select` 属性支持配置弹窗部分信息

---

package.json
packages/base/src/card-group/item.tsx
packages/hooks/src/common/use-in-view/index.ts
packages/hooks/src/common/use-in-view/use-in-view.ts
packages/hooks/src/index.ts
packages/shineout/src/card-group/__doc__/changelog.cn.md
packages/shineout/src/card-group/__doc__/index.md
packages/shineout/src/card-group/__example__/t-001-lazyout.tsx

perf: 优化`CardGroup` 大数据量下的渲染性能

---

package.json
packages/base/src/card-group/item.tsx
packages/base/src/card-group/lazyload.tsx

fix: card-group 懒加载优化

---

package.json
packages/base/src/card-group/item.tsx

fix: card-group懒加载进一步优化

---

packages/hooks/src/common/use-in-view/use-in-view.ts
packages/shineout/src/card-group/__test__/__snapshots__/cardGroup.spec.tsx.snap

fix: 兼容CardGroup测试用例

---

package.json
packages/base/src/card-group/item.tsx
packages/base/src/card-group/item.type.ts

perf: card-group perf

---

packages/base/src/card-group/item.tsx
packages/shineout/src/card-group/__test__/__snapshots__/cardGroup.spec.tsx.snap

fix: fix card-group

---

packages/base/src/table/tr.tsx

fix: 修复Table合并行的hover效果

---

package.json
packages/base/src/table/tr.tsx
packages/shineout/src/table/__doc__/changelog.cn.md

- 修复 `Table` 点击 checkbox 展开行的问题

fix: 修复 `Table` 点击 checkbox 展开行的问题

---

package.json
packages/base/src/date-picker/date-picker.tsx
packages/shineout-style/src/select/select.ts
packages/shineout/src/date-picker/__doc__/changelog.cn.md
packages/shineout/src/select/__doc__/changelog.cn.md

- 修复 `Select` 禁用模式下 icon 样式异常
- 修复 `DatePicker` 禁用后可聚焦的问题

fix: 修复 `Select` 禁用模式下 icon 样式异常、`DatePicker` 禁用后可聚焦的问题

---

package.json
packages/shineout-style/src/table/table.ts

fix: 修复Table原生滚动时,固定列的阴影重影问题

---

package.json
packages/base/src/select/result.tsx
packages/shineout/src/select/__doc__/changelog.cn.md

- 修复 `Select` 在 value 为空对象时 placeholder 失效的问题

fix: 修复 `Select` 在 value 为空对象时 placeholder 失效的问题

---

package.json
packages/base/src/select/result.tsx

fix: 修复Select组件回显值可能出现[object object]

---

package.json
packages/base/src/select/result.tsx
packages/shineout/src/select/__doc__/changelog.cn.md

- 优化 `Select` 组件默认 placeholder 占位形式
result 中实际渲染的 dom 为空内容时，依然用基础 placeholder 形式渲染

feat: 优化 `Select` 组件默认 placeholder 占位形式

---

package.json
packages/base/src/tabs/tabs.tsx
packages/shineout/src/tabs/__doc__/changelog.cn.md
packages/shineout/src/tabs/__test__/tabs.spec.tsx

fix: 修复 `Tabs` 折叠后Tabs.Panel内容溢出展示的问题

---

package.json
packages/hooks/src/components/use-form/use-form-control/use-form-control.ts

fix: 修复 Form 校验失效的问题

---

package.json
packages/shineout-style/src/date-picker/date-picker.ts
packages/shineout/src/date-picker/__doc__/changelog.cn.md

- 修复 `DatePicker` 组件 `align` 属性失效的问题

fix: 修复 `DatePicker` 组件 `align` 属性失效的问题

---

packages/shineout/src/form/__doc__/changelog.cn.md

fix: changelog

---

packages/base/src/select/select.tsx

chore: 调整 Select 类型

---

packages/hooks/src/components/use-form/use-form-control/use-form-control.ts

fix: 修复 ts 错误

---

packages/shineout/src/table/__doc__/changelog.cn.md

chore: release 3.5.3-beta.3

---

packages/base/src/form/form-fieldset.tsx

- Form.FieldSet children render

fix: Form.FieldSet children render

---

package.json
packages/hooks/src/components/use-form/use-form-control/use-form-control.ts
packages/hooks/src/components/use-form/use-form.ts
packages/shineout/src/form/__doc__/changelog.cn.md
packages/shineout/src/form/__example__/test-001-base-form.tsx

- 修复 `Form` 组件 `onChange` 执行多次且数组嵌套字段模式下死循环的问题
98b3c7c5-2d33-429a-9257-e79fbf2c59a0
Regression: since v3.4.4,v3.5.2

fix: 修复 `Form` 组件 `onChange` 执行多次且数组嵌套字段模式下死循环的问题

---

package.json
packages/base/src/steps/step.tsx
packages/base/src/steps/step.type.ts
packages/base/src/steps/steps-context.type.ts
packages/base/src/steps/steps.tsx
packages/base/src/steps/steps.type.ts
packages/shineout/src/steps/__doc__/changelog.cn.md
packages/shineout/src/steps/__example__/09-click-disabled.tsx

feat: 优化 `Steps` 组件 `disabled` 用法

---

packages/hooks/src/utils/warning.ts
packages/shineout/src/table/__example__/07-02-virtual-scroll.tsx

feat: 开发模式下相同的错误信息仅报一次

---

package.json
packages/base/src/table/table.tsx
packages/base/src/table/tbody.tsx
packages/base/src/table/tbody.type.ts
packages/base/src/table/tr.tsx
packages/hooks/src/components/use-table/use-table.type.ts
packages/shineout/src/table/__doc__/changelog.cn.md

- `Table` 新增 `expandIcon` 属性，支持自定义渲染可展开行的 icon 区域内容

feat: `Table` 新增 `expandIcon` 属性，支持自定义渲染可展开行的 icon 区域内容

---

package.json
packages/base/src/table/tr.tsx
packages/base/src/virtual-scroll/scroll.tsx
packages/base/src/virtual-scroll/virtual-scroll-list.tsx
packages/shineout/src/table/__example__/test-006-fix-online.tsx
packages/shineout/src/table/__example__/test-006-fix-scroll-y.tsx

- 优化Table合并行的虚拟列表和非虚拟列表的删除行之后的渲染问题(Regression: since 3.5.4-beta)

fix: 优化Table合并行的虚拟列表和非虚拟列表的删除行之后的渲染问题(Regression: since 3.5.4-beta)

---

package.json
packages/shineout/src/table/__doc__/changelog.cn.md

Release 3.5.4

---

package.json
packages/base/src/virtual-scroll/scroll.tsx

fix: 避免Table垂直方向上的滚动条抖动现象

---

packages/shineout/src/spin/__example__/01-base-1.tsx
packages/shineout/src/spin/__test__/__snapshots__/spin.spec.tsx.snap
packages/shineout/src/transfer/__test__/__snapshots__/transfer.spec.tsx.snap

doc: 修改Spin组件基本用法

---

packages/base/src/form/form-item.tsx
packages/base/src/form/form.tsx
packages/hooks/src/components/use-form/use-form.ts
packages/hooks/src/components/use-form/use-form.type.ts
packages/shineout/src/form/__doc__/changelog.cn.md
packages/shineout/src/form/__example__/003-label-3.tsx

- `Form` 新增 `colon` 属性，用于控制 label 是否显示冒号

feat: `Form` 新增 `colon` 属性，用于控制 label 是否显示冒号

---

docs/markdown/shineout/theme.md
docs/pages/markdown/style.ts
docs/theme/index.tsx
docs/theme/layout/desktop/menu/index.tsx
packages/shineout-style/src/normalize.ts
packages/theme/src/utils/token-setter.ts

feat: 新增 `theme` 文档

---

docs/markdown/shineout/theme.md

feat: 补充 theme 文档说明

---

package.json
packages/hooks/src/common/use-position-style/index.ts
packages/shineout/src/popover/__doc__/changelog.cn.md

- 修复 `Popover` 组件受控为 true 但不在视口范围内时无法展示的问题

fix: 修复 `Popover` 组件受控为 true 但不在视口范围内时无法展示的问题

---

docs/markdown/shineout/theme.md
docs/pages/markdown/style.ts

feat: 更新 theme 文档

---

packages/base/src/tabs/tabs-header.tsx

fix：delete unusage code in tabs-header

fix: 删除tabs中无用代码

---

packages/base/src/tabs/tabs-panel.tsx
packages/base/src/tabs/tabs-panel.type.ts
packages/shineout/src/tabs/tabs-panel.type.ts

- 修改向indexInTabs位置插入tabData的方式

fix: 修改向indexInTabs位置插入tabData的方式

---

package.json
packages/base/src/form/form-footer-context.tsx
packages/base/src/form/form.tsx
packages/shineout/src/modal/__doc__/changelog.cn.md
packages/shineout/src/modal/__example__/test-06-form-tabs-submit.tsx

- 修复 `Modal.Submit` 在存在多个Form组件切换时，点击触发的onSubmit的value不正确的问题
9361ecb3-019b-48af-8b54-895ff5b273e3

fix: 修复 `Modal.Submit` 在存在多个Form组件切换时，点击触发的onSubmit的value不正确的问题

---

package.json

fix: 修改版本号

---

packages/shineout/src/date-picker/__example__/test-006-bbl.tsx

chore: add remote bbl useage

---

packages/shineout/src/button/__example__/s-001-base.tsx
packages/shineout/src/button/__test__/__snapshots__/button.spec.tsx.snap

fix: 更新Button示例

---

packages/shineout/src/cascader/__test__/__snapshots__/cascader.spec.tsx.snap
packages/shineout/src/menu/__test__/__snapshots__/menu.spec.tsx.snap
packages/shineout/src/radio/__test__/__snapshots__/radio.spec.tsx.snap
packages/shineout/src/tree/__test__/__snapshots__/tree.spec.tsx.snap

chore: update test snap

---

package.json
packages/shineout-style/src/spin/ring.ts
packages/shineout/src/spin/__doc__/changelog.cn.md

fix: 修复 `Spin` 的ring样式在微前端框架下颜色不继承的问题

---

package.json
packages/shineout-style/src/steps/steps.ts
packages/shineout/src/steps/__doc__/changelog.cn.md

fc61b8b4-2cd1-47e3-8ce0-083202847675

fix: 修复 `Steps` 组件 `type='arrow'` 模式下小尺寸样式异常的问题

---

package.json
packages/shineout-style/src/steps/steps.ts
packages/shineout/src/steps/__doc__/changelog.cn.md

- 修复 `Steps` 在 `size='large'` 情况下样式异常的问题
d9c89e98-5d13-47aa-87dc-13d343c0b11b

fix: 修复 `Steps` 在 `size='large'` 情况下样式异常的问题

---

package.json
packages/base/src/checkbox/checkbox.tsx
packages/base/src/checkbox/checkbox.type.ts
packages/shineout/src/checkbox/__doc__/changelog.cn.md

- 修复 `Checkbox.Group` 在嵌套情况下影响内部选中状态的问题
b003091f-9794-49a2-8dc0-a42751fa16c9

fix: 修复 `Checkbox.Group` 在嵌套情况下影响内部选中状态的问题

---

package.json
packages/hooks/src/components/use-form/use-form.ts
packages/hooks/src/utils/object.ts
packages/shineout/src/form/__doc__/changelog.cn.md

30276ca9-c083-43d6-95bd-ab7ead1affed

fix: 修复 `Form` 的FormRef.validateFields方法校验数组类型字段不生效的问题

---

packages/base/src/form/form.type.ts

fix: 修复Form中validate实例方法类型定义错误

---

package.json
packages/base/src/upload/button.tsx
packages/base/src/upload/button.type.ts
packages/shineout/src/upload/__doc__/changelog.cn.md

fix: 修复 `Upload.Button` 不支持mode=outline的问题

---

package.json
packages/hooks/src/utils/object.ts
packages/shineout/src/form/__doc__/changelog.cn.md
packages/shineout/src/tree/__example__/07-loader.tsx

fix: 修复 `Form` 的 FormRef.validateFields('friends[1]')这种用法不生效的问题

---

package.json
packages/base/src/cascader/cascader.tsx
packages/hooks/src/common/use-filter/use-filter.ts
packages/shineout/src/cascader/__doc__/changelog.cn.md
packages/shineout/src/cascader/__example__/05-loader.tsx
packages/shineout/src/form/__doc__/changelog.cn.md

- 修复 `Cascader` 多选模式下搜索时没有自动展开命中结果的问题（Regression: since v3.1.6）

fix: 修复 `Cascader` 多选模式下搜索时没有自动展开命中结果的问题（Regression: since v3.1.6）

---

packages/base/src/cascader/node.tsx
packages/shineout/src/cascader/__doc__/changelog.cn.md

- `Cascader` 非hover的多选模式下，末级节点支持整个节点区域点击选中checkbox

fix: `Cascader` 非hover的多选模式下，末级节点支持整个节点区域点击选中checkbox

---

package.json
packages/shineout/src/transfer/__doc__/changelog.cn.md

fix: 3.5.8-beta.4

---

package.json
packages/hooks/src/components/use-form/use-form.ts
packages/shineout/src/form/__doc__/changelog.cn.md

fix: 修复 `Form` 的 `FieldSet`嵌套使用后，子级的insert value触发了父级的校验的问题

---

package.json
packages/base/src/cascader/cascader.tsx
packages/base/src/cascader/cascader.type.ts
packages/hooks/src/components/use-cascader/use-cascader.ts
packages/hooks/src/components/use-cascader/use-cascader.type.ts
packages/hooks/src/components/use-tree/index.ts
packages/hooks/src/components/use-tree/use-tree.ts
packages/hooks/src/components/use-tree/use-tree.type.ts
packages/hooks/src/utils/is.ts
packages/shineout/src/cascader/__doc__/changelog.cn.md
packages/shineout/src/cascader/__example__/04-disabled.tsx
packages/shineout/src/cascader/__test__/__snapshots__/cascader.spec.tsx.snap

- Cascader 新增 `disabled` 配置模式，支持实时计算 disabled 状态

feat: Cascader 新增 `disabled` 配置模式，支持实时计算 disabled 状态

---

package.json
packages/base/src/tabs/tabs.tsx
packages/shineout/src/tabs/__doc__/changelog.cn.md

部分场景下 Tabs 首次渲染可能受到外部影响导致横线位置计算错误

feat: 调整 `Tabs` 首次挂载布局更新方式

---

packages/shineout/src/collapse/__doc__/changelog.cn.md
packages/shineout/src/collapse/__test__/__snapshots__/collapse.spec.tsx.snap
packages/shineout/src/collapse/__test__/collapse.spec.tsx

feat: 更新测试用例

---

packages/shineout/src/tree-select/__test__/__snapshots__/treeSelect.spec.tsx.snap

chore: update teeSelect snap

---

packages/base/src/index.ts
packages/shineout/src/index.ts
scripts/ejs/base.index.ts.ejs
scripts/ejs/shineout.index.ts.ejs

fix: ejs模板增加icons导出的声明

---

packages/base/src/transfer/transfer.tsx

fix: 修复Transfer组件自定义children是动态时更新不生效

---

docs/theme/components/markdown/api.tsx

feat: 优化文档 api 样式

---

packages/hooks/src/components/use-form/use-form.ts

ec1e6f18-940b-40b5-9f5a-a33fac29bef9

fix:  修复Form scrollToField 在复杂布局中不生效

---

packages/shineout/src/form/__doc__/changelog.cn.md

chore: git pr 973

---

package.json
packages/base/src/upload/upload.tsx
packages/shineout/src/upload/__doc__/changelog.cn.md

- 修复 `Upload` 组件 `webkitdirectory` 属性失效的问题
8b142161-c71c-4de5-bc0f-992603933517

fix: 修复 `Upload` 组件 `webkitdirectory` 属性失效的问题

---

package.json
packages/base/src/tree-select/tree-select.tsx
packages/base/src/tree/tree.tsx
packages/base/src/tree/tree.type.ts
packages/hooks/src/components/use-tree/use-tree.ts
packages/hooks/src/components/use-tree/use-tree.type.ts
packages/shineout/src/tree-select/__doc__/changelog.cn.md
packages/shineout/src/tree-select/__example__/10-virtual.tsx
packages/shineout/src/tree/__example__/12-virtual.tsx

fix: 修复 `TreeSelect` 过滤筛选情况下选择数据不完整的问题

---

package.json
packages/hooks/src/utils/dom/element.tsx
packages/hooks/src/utils/lazyload.ts
packages/shineout/src/date-picker/__test__/datePicker.spec.tsx
packages/shineout/src/image/__doc__/changelog.cn.md

7619807b-2ba3-49e9-906c-655b5887d44d

fix: 修复 `Image` 在容器为 'absolute' 定位情况下 `lazy` 属性可能失效的问题

---

package.json
packages/base/src/date-picker/day.tsx
packages/shineout-style/src/date-picker/date-picker.ts
packages/shineout/src/date-picker/__doc__/changelog.cn.md
packages/theme/src/date-picker/date-picker.ts
packages/theme/src/date-picker/token.ts
packages/theme/src/date-picker/type.ts

e4582d81-973a-42f7-8717-eb8d13862690

fix: 修复 `Datepicker` 仅开启 `needConfirm` 属性情况下不展示今天按钮的问题、调整小尺寸日期组件样式

---

packages/shineout-style/src/version.ts
packages/shineout/src/index.ts
packages/shineout/src/steps/interface.ts

feat: 更新 Steps 子组件 Step 类型

---

packages/shineout/src/select/__example__/10-02-filter.tsx
packages/shineout/src/tree/__example__/14-virtual.tsx

feat: 调整文档描述信息

---

package.json
packages/base/src/image/image.tsx
packages/base/src/image/image.type.ts
packages/base/src/image/index.ts
packages/base/src/upload/upload.tsx
packages/base/src/upload/upload.type.ts
packages/shineout/src/image/__doc__/changelog.cn.md
packages/shineout/src/image/image.type.ts
packages/shineout/src/upload/__doc__/changelog.cn.md

- `Upload` 组件新增 `hideHandler` 属性，支持隐藏默认触发器，增强 customResult 返回属性
- `Image` 组件新增 `customRenderHoverMask` 属性，支持自定义渲染鼠标移入组件时的遮罩层内容

feat: `Upload` 组件新增 `hideHandler` 属性、`Image` 组件新增 `customRenderHoverMask` 属性

---

packages/base/src/input/simple-input.tsx
packages/base/src/input/use-input-common.tsx
packages/base/src/table/table.tsx
packages/hooks/src/common/use-pagination-list/index.tsx
packages/hooks/src/components/use-table/use-table-filter.ts

fix: Table筛选搭配前端分页的显示问题

---

package.json
packages/base/src/upload/upload.tsx
packages/base/src/upload/upload.type.ts
packages/shineout/src/upload/__doc__/changelog.cn.md

- `Upload` 组件增强 `CustomResult` 返回内容，支持返回原文件组件实例

feat: `Upload` 组件增强 `CustomResult` 返回内容，支持返回原文件组件实例

---

package.json
packages/base/src/upload/upload.tsx
packages/base/src/upload/upload.type.ts
packages/shineout/src/upload/__doc__/changelog.cn.md

feat: `Upload` 组件增强 `CustomResult` 返回内容，新增返回原文件组件（成功文件）实例

---

package.json
packages/base/src/upload/dragger.tsx
packages/base/src/upload/dragger.type.ts
packages/base/src/upload/index.ts
packages/base/src/upload/upload.type.ts
packages/shineout-style/src/upload/upload.ts
packages/shineout/src/upload/__doc__/changelog.cn.md
packages/shineout/src/upload/dragger.tsx
packages/shineout/src/upload/dragger.type.ts
packages/shineout/src/upload/index.ts
packages/shineout/src/upload/interface.ts

fix: 修复 `Upload.Dragger` 子组件缺失的问题

---

docs/theme/components/example/style.ts
package.json
packages/base/src/tree-select/tree-select.tsx
packages/base/src/tree/tree.tsx
packages/base/src/tree/tree.type.ts
packages/hooks/src/components/use-tree/use-tree.ts
packages/shineout-style/src/tree/tree.ts
packages/shineout/src/tree-select/__example__/10-virtual.tsx
packages/shineout/src/tree/__doc__/changelog.cn.md

- 修复 `TreeSelect` 组件开 `virtual` 和 `defaultExpandedAll` 后，过滤数据不展开的问题
- 修复 `TreeSelect` 节点样式不对齐对问题

fix: 修复 `TreeSelect` 组件开 `virtual` 和 `defaultExpandedAll` 后，过滤数据不展开的问题、节点样式不对齐对问题

---

packages/base/src/pagination/pagination-simple.tsx

fix: 移除PaginationSimple组件中的current属性

---

scripts/doc-page.ejs

chore: 示例稳定的注释信息展示出来

---

package.json
packages/hooks/src/components/use-table/use-table-filter.ts
packages/shineout/src/table/__doc__/changelog.cn.md
packages/shineout/src/table/__test__/table.spec.tsx

fix: 修复 `Table` 的columns是动态值时，column.filter的过滤功能意外的被重置的问题

---

package.json
packages/hooks/src/components/use-form/use-form.ts
packages/shineout/src/form/__doc__/changelog.cn.md
packages/shineout/src/form/__example__/test-004-deley-0.tsx

ef7946d5-b05d-4459-86a6-7c404ee63868

fix: 修复 `Form` 同时设置 value 和 names为数组的DatePicker并发渲染时，value未按照预期设置进去的问题

---

package.json
packages/shineout-style/src/input/input-border.ts
packages/shineout/src/date-picker/__doc__/changelog.cn.md

fix: 修复 `DatePicker` 弹出层层级问题

---

package.json
packages/hooks/src/common/use-in-view/use-in-view.ts
packages/hooks/src/utils/dom/element.tsx
packages/shineout/src/card-group/__doc__/changelog.cn.md

fix: 优化 `CardGroup` 在非滚动容器下也能支持懒加载

---

package.json
packages/base/src/card-group/item.tsx
packages/base/src/card-group/lazyload.tsx
packages/hooks/src/utils/dom/element.tsx
packages/shineout/src/card-group/__doc__/changelog.cn.md

fix: 优化 `CardGroup.Item` 在非滚动容器下也能支持懒加载

---

packages/hooks/src/common/use-position-style/check-position.ts
packages/shineout/src/popover/__doc__/changelog.cn.md

fb36dc13-5837-460f-ab98-9ce75186d375

feat: 优化 `Popover` 的 `adjust` 属性，支持弹出层位置实时跟随父元素尺寸变化

---

packages/hooks/src/components/use-input/use-input-number.ts
packages/shineout/src/input/__doc__/changelog.cn.md

17ab9bab-a7df-4486-ac3f-81e9259ff4a7

fix: 修复 `Input.Number` 输入“0.0”这种格式时小数点丢失的问题

---

docs/pages/changelog/index.tsx
package.json
packages/theme/src/tree/token.ts
packages/theme/src/tree/tree.ts
packages/theme/src/tree/type.ts

Release 3.6.1

---

package.json
packages/base/src/tabs/tab.tsx
packages/base/src/tabs/tab.type.ts
packages/base/src/tabs/tabs-header.tsx
packages/base/src/tabs/tabs-panel.tsx
packages/base/src/tabs/tabs-panel.type.ts
packages/base/src/tabs/tabs.tsx
packages/base/src/tabs/tabs.type.ts
packages/shineout/src/tabs/__doc__/changelog.cn.md

fix: 修复 `Tabs.Panel` 设置 `background` 属性失效的问题

---

packages/hooks/src/components/use-form/use-form.ts
packages/shineout/src/form/__example__/test-004-deley-0.tsx

- 改回3.6.1-beta.4之前的行为，用户使用时需要给相应的字段加上reserveAble
6dddee40-baca-46a0-ae74-256dd068f26a

fix: 修正Form内部update行为(Regression: since v3.6.1-beta.4)

---

packages/base/src/transfer/transfer.tsx
packages/shineout/src/transfer/__doc__/changelog.cn.md

88961b22-793a-46fc-9ea1-571481b83d15

fix: 修复 `Transfer` 动态设置 `loading` 不生效的问题

---

docs/pages/changelog/index.tsx

chore: beta版本文档的排序展示

---

package.json

fix: fix build publish script

---

docs/theme/components/example/index.tsx
docs/theme/components/example/style.ts
docs/theme/components/markdown/api.tsx
docs/theme/components/markdown/doc.tsx
docs/theme/components/style.ts
packages/shineout/src/input/__example__/04-03-group-validate.tsx
packages/shineout/src/tree/__example__/03-line.tsx
packages/shineout/src/tree/__example__/04-02-expandall.tsx
packages/shineout/src/tree/__example__/06-onchange.tsx
packages/shineout/src/tree/__example__/08-drag.tsx
packages/shineout/src/tree/__example__/09-drag-style.tsx
packages/shineout/src/tree/__example__/10-inline-node.tsx
packages/shineout/src/tree/__example__/11-action-on-click.tsx
packages/shineout/src/tree/__example__/12-highlight.tsx
packages/shineout/src/tree/__example__/13-highlight-control.tsx
packages/shineout/src/tree/__example__/14-virtual.tsx

chore: 示例文档的api能跳转至api页面

---

docs/theme/components/example/index.tsx
docs/theme/components/example/style.ts
docs/theme/components/example/tip/index.tsx
packages/shineout/src/tree/__example__/03-line.tsx
packages/shineout/src/tree/__example__/04-02-expandall.tsx
packages/shineout/src/tree/__example__/06-onchange.tsx
packages/shineout/src/tree/__example__/07-loader.tsx
packages/shineout/src/tree/__example__/08-drag.tsx
packages/shineout/src/tree/__example__/09-drag-style.tsx
packages/shineout/src/tree/__example__/10-inline-node.tsx
packages/shineout/src/tree/__example__/11-action-on-click.tsx
packages/shineout/src/tree/__example__/12-highlight.tsx
packages/shineout/src/tree/__example__/13-highlight-control.tsx
packages/shineout/src/tree/__example__/14-virtual.tsx

chore: 更新文档api跳转方式

---

package.json

chore: 更新版本号至 3.6.2

---

package.json
packages/base/src/sticky/sticky.tsx
packages/shineout/src/sticky/__doc__/changelog.cn.md
packages/shineout/src/sticky/__example__/01-base.tsx

fix: 修复 Sticky 组件 onChange 不触发的问题，更新版本号至 3.6.3-beta.1

---

package.json
packages/base/src/table/table.tsx
packages/base/src/table/table.type.ts
packages/base/src/table/tbody.tsx
packages/base/src/table/thead.tsx
packages/base/src/table/tr.tsx
packages/base/src/virtual-scroll/scroll-table.tsx
packages/hooks/src/components/use-table/use-table-layout.tsx
packages/hooks/src/components/use-table/use-table-row.tsx
packages/hooks/src/components/use-table/use-table-virtual.tsx
packages/shineout-style/src/table/table.ts
packages/shineout/src/table/__doc__/changelog.cn.md
packages/shineout/src/table/__test__/table.spec.tsx

- 修复 `Table` 的colgroup平均分配时产生的小数位像素在浏览器渲染时偶现的单元格垂直边框对不齐问题
- 优化 `Table` 合并行|列的hover渲染性能

Perf table

---

package.json
packages/shineout-style/src/cascader/cascader.ts
packages/shineout-style/src/tree-select/tree-select.ts
packages/shineout/src/cascader/__doc__/changelog.cn.md
packages/shineout/src/tree-select/__doc__/changelog.cn.md

fix: 修复 `Cascader`、`TreeSelect` 最大高度限制失效的问题（默认 max-height 应为 80px）

---

packages/base/src/form/form-flow.tsx

fix: 调整 `Form.Flow` 类型

---

packages/base/src/tree-select/tree-select.type.ts
packages/shineout/src/tree-select/__doc__/changelog.cn.md

feat: `TreeSelect` 新增 `contentClass` 属性，功能同 `Tree` 组件属性

---

package.json
packages/base/src/tree/tree-content.tsx
packages/base/src/tree/tree.type.ts
packages/shineout-style/src/tree/tree.ts
packages/shineout/src/tree/__doc__/changelog.cn.md

fix: 优化 `Tree` 的节点鼠标手势，节点content区域的鼠标手势修改为pointer

---

packages/base/src/tree-select/tree-select.tsx

修复 3.6.3 新增的属性的缺陷，不单独记录 changlog

fix: 修复 `TreeSelect` 设置 `contentClass` 后对选中节点无效的问题

---

package.json

chore: 更新版本号至 3.6.3

---

packages/base/src/select/list.tsx
packages/base/src/select/select.tsx
packages/base/src/select/select.type.ts

4232b2b9-1d07-4a2f-a38b-791acb616bfc

fix: 修复 `Select` 搜索内容后选项被遮挡的问题

---

packages/base/src/select/list.tsx

chore: 去除无效内容

---

package.json
packages/base/src/select/result.tsx
packages/shineout/src/select/__doc__/changelog.cn.md

19bbdb1b-4790-4e61-a36e-7efb3008cc6b

fix: 修复 `Select` 开启过滤后打开面板快速再次聚焦时可能清空输入框文本内容的问题

---

packages/base/src/tree/tree-virtual.tsx
packages/base/src/tree/tree.tsx
packages/base/src/tree/tree.type.ts
packages/shineout/src/tree/__doc__/changelog.cn.md

fix: 修复 `Tree` 传入 `rowsInView` 属性失效的问题

---

package.json
packages/base/src/tree-select/tree-select.tsx
packages/base/src/tree-select/tree-select.type.ts
packages/shineout/src/tree-select/__doc__/changelog.cn.md

fix: 修复 `TreeSelect` 的 `onFilter` ts 类型和第二参数丢失的问题

---

package.json
packages/base/src/tabs/tabs.tsx
packages/base/src/tabs/tabs.type.ts
packages/shineout/src/tabs/__doc__/changelog.cn.md

feat: `Tabs` 新增 `renderTabsHeader` 属性，支持自定义渲染头部内容

---

package.json

chore: 更新版本号至 3.6.4-beta.8

---

package.json

chore: 更新版本号至 3.6.4

---

package.json
packages/hooks/src/components/use-upload/use-upload.ts

fix: 更新版本号至 3.6.5-beta.7，并优化Upload文件状态管理逻辑

---

package.json
packages/hooks/src/components/use-form/use-form.ts

fix: 撤回Form.Flow的onChange行为(Regression: since v3.6.5-beta.3)

---

package.json
packages/hooks/src/components/use-form/use-form.ts

fix: 更新版本号至 3.6.5-beta.9，并优化useForm组件的值处理逻辑

---

package.json
packages/base/src/form/form-footer-context.tsx
packages/base/src/modal/modal-submit.tsx
packages/hooks/src/components/use-form/use-form.ts
packages/shineout/src/card/__test__/card.spec.tsx
packages/shineout/src/modal/__doc__/changelog.cn.md

161bed23-da39-4438-a8cc-c4a612e7dc69

fix: 修复Modal.Submit的onClick事件比form.submit先执行的问题

---

package.json
packages/base/src/table/table.tsx
packages/base/src/table/table.type.ts
packages/shineout/src/table/__example__/06-bottom-scrollbar.tsx

fix: 更新版本号至3.7.0-beta.13，并移除Table不必要的scrollContainer属性

---

package.json
packages/base/src/tabs/tabs-panel.tsx
packages/shineout-style/src/modal/modal.ts
packages/shineout/src/tabs/__doc__/changelog.cn.md
packages/shineout/src/tabs/__example__/03-position.tsx
packages/shineout/src/transfer/__doc__/changelog.cn.md

e021155e-4c3f-4aef-97ff-815a888a74e3

fix: 修复 `Tabs.Panel` 设置 `background` 非预期的影响到shape为button和fill的样式（Regression: since v3.6.2）

---

docs/theme/components/markdown/api.tsx

fix: 优化文档的api跳转

---

package.json
packages/base/src/select/select.tsx
packages/base/src/tree-select/tree-select.tsx
packages/base/src/tree-select/tree-select.type.ts
packages/shineout/src/select/__doc__/changelog.cn.md
packages/shineout/src/select/__example__/01-04-renderCompressed.tsx
packages/shineout/src/tree-select/__doc__/changelog.cn.md
packages/shineout/src/tree-select/__example__/03-02-renderCompressed.tsx

feat: TreeSelect Select 新增 `renderCompressed` 属性，支持自定义渲染合并选项

---

packages/base/src/cascader/cascader.tsx
packages/shineout/src/cascader/__example__/11-render-option-list.tsx

fix: 增加Cascader 全选用法示例

---

package.json
packages/base/src/date-picker/date-picker.tsx
packages/hooks/src/components/use-popup/use-popup.ts
packages/shineout/src/date-picker/__doc__/changelog.cn.md

7c09a0c3-a200-4bd5-900e-e35b84784b55

fix: 更新 DatePicker 组件，修复受控用法下 onChange 多次调用的问题

---

package.json

chore: 3.7.0-beta.29

---

package.json

chore: release 3.6.7

---

package.json
packages/base/src/carousel/carousel.tsx
packages/base/src/carousel/carousel.type.ts
packages/shineout/src/carousel/__doc__/changelog.cn.md

feat: `Carousel` 新增 `showIndicator` 和 `itemClassName` 属性

---

packages/shineout-style/src/table/table.ts

feat: 优化 Table empty 居中样式

---

packages/hooks/src/components/use-form/use-form.type.ts

fix: 移除use-form.type.ts中的无用属性settingMap

---

package.json
packages/shineout-style/src/tree-select/tree-select.ts
packages/shineout/src/tree-select/__doc__/changelog.cn.md
packages/theme/src/tree-select/token.ts
packages/theme/src/tree-select/tree-select.ts
packages/theme/src/tree-select/type.ts

feat: `TreeSelect` 新增禁用选项背景色的 token

---

packages/base/src/tree/tree-content.tsx
packages/shineout-style/src/tree-select/tree-select.ts
packages/shineout/src/tree/__test__/__snapshots__/tree.spec.tsx.snap

feat: 调整 TreeSelect hover 背景色生效作用域

---

package.json

chore: release 3.7.1

---

package.json
packages/hooks/src/common/use-position-style/index.ts
packages/shineout-style/src/popover/popover.ts
packages/shineout-style/src/tooltip/tooltip.ts
packages/shineout/src/popover/__doc__/changelog.cn.md
packages/shineout/src/popover/__test__/__snapshots__/popover.spec.tsx.snap
packages/shineout/src/popover/__test__/popover.spec.tsx
packages/shineout/src/tooltip/__doc__/changelog.cn.md
packages/shineout/src/tooltip/__test__/tooltip.spec.tsx

chore: 更新版本号至 3.8.0-beta.2，增强 `Popover` 和 `Tooltip` 组件的弹出动画效果

---

package.json
packages/base/src/date-picker/date-picker.tsx
packages/base/src/date-picker/day.tsx
packages/base/src/date-picker/picker.tsx
packages/base/src/date-picker/picker.type.ts
packages/base/src/input/simple-input.tsx
packages/hooks/src/components/use-datepicker/use-date.ts
packages/hooks/src/components/use-datepicker/use-date.type.ts
packages/hooks/src/components/use-datepicker/use-datepicker-range.ts
packages/hooks/src/components/use-form/use-form.ts
packages/shineout/src/date-picker/__doc__/changelog.cn.md
packages/shineout/src/form/__doc__/changelog.cn.md
packages/shineout/src/input/__doc__/changelog.cn.md

742afba9-a1fb-4fa5-aeb2-9a980bf72a7e

feat: 修复 `DatePicker` 设置 `allowSingle` 后无法点击已选日期取消选中的问题

---

package.json

chore: 3.7.3-beta.5

---

packages/hooks/src/components/use-datepicker/use-date.ts
packages/shineout-style/src/index.ts
packages/shineout-style/src/version.ts
packages/shineout/src/index.ts

fix: 调整 `DatePicker` ts 类型

---

package.json
packages/shineout-style/src/skeleton/skeleton.ts
packages/shineout/src/skeleton/__doc__/changelog.cn.md

fix: 更新版本号至 3.7.3-beta.6，修复 `Skeleton` 组件在微前端下动画效果不生效的问题

---

docs/markdown/shineout/changelog-common.md
package.json
packages/shineout-style/src/version.ts
packages/shineout/src/index.ts
scripts/ejs/shineout.index.ts.ejs

chore: 更新版本号至 3.8.0-beta.4，并修复 `utils` 导出名称错误的问题

---

package.json
packages/base/src/cascader/node.tsx
packages/shineout/src/cascader/__doc__/changelog.cn.md

fix: 更新版本号至 3.7.3-beta.7，修复 `Cascader` 组件在多选模式下末级叶子节点勾选框点击失效的问题

---

package.json

feat: 3.7.3-beta.8

---

docs/markdown/shineout/changelog-common.md
package.json
packages/theme/src/utils/token-setter.ts

feat: `setToken` 新增忽略扩展样式开关 `ignoreExtra` 用于屏蔽兼容老版本组件的额外 cssvar

---

docs/theme/layout/desktop/menu/index.tsx
docs/theme/layout/desktop/menu/menu-item.tsx
packages/shineout/src/modal/__example__/01-base.tsx
packages/shineout/src/modal/__test__/__snapshots__/modalSnapshot.spec.tsx.snap

feat: 文档的高亮目录自动跳转

---

packages/base/src/form/form-flow.type.ts
packages/base/src/form/index.ts
packages/shineout/src/form/form.type.ts
packages/shineout/src/form/interface.ts

feat: 🎸 Form新增FlowProps及Datum类型导出

---

package.json
packages/hooks/src/components/use-form/use-form-context.ts
packages/shineout/src/form/__doc__/changelog.cn.md

18f8314a-6387-4077-876f-77aab188c882

fix: 优化 useFormRef 函数，使用 useState 替代 useRef 管理表单引用状态

---

packages/shineout/src/tree-select/__test__/treeSelect.spec.tsx

test: 增加 TreeSelect 组件在多选模式下的 onChangeAddition 回调测试，验证选中和取消选中的状态及参数

---

package.json
packages/base/src/dropdown/Item.tsx
packages/shineout/src/tooltip/__doc__/changelog.cn.md

bbabf2ea-944c-42b6-87ca-eff88071586c

fix: 更新版本号至 3.7.5-beta.1，并修复 `Tooltip` 在 `Dropdown` 中使用时的 className传递问题

---

package.json

chore: 3.7.5-beta.2

---

package.json
packages/hooks/src/components/use-datepicker/use-datepicker-format.ts
packages/shineout/package.json
packages/shineout/src/date-picker/__doc__/changelog.cn.md
pnpm-lock.yaml

04896c5b-93fb-4b20-b17c-54c07fa4e4b4

fix: 更新版本号至 3.7.5-beta.5，并修复 `DatePicker` 组件的 `formatResult` 属性在 `type` 为 `month` 时切换月份时展示结果不正确的问题

---

package.json
packages/base/src/alert/alert.tsx
packages/shineout/src/alert/__doc__/changelog.cn.md

6563b11f-9189-49e2-8a88-29040dac80f0

fix: 修复 `Alert` 传入空字符串 `title` 属性也能渲染结构的问题

---

package.json
packages/base/src/cascader/cascader.type.ts
packages/base/src/select/result.tsx
packages/base/src/select/result.type.ts
packages/base/src/select/select.type.ts
packages/base/src/tree-select/tree-select.type.ts
packages/shineout-style/src/cascader/cascader.ts
packages/shineout-style/src/select/select.ts
packages/shineout-style/src/tree-select/tree-select.ts
packages/shineout/src/cascader/__example__/big-biz-data.js
packages/shineout/src/cascader/__example__/test-02-virtual-compressed.tsx
packages/shineout/src/select/__doc__/changelog.cn.md

fix: 更新版本号至 3.7.5-beta.11，新增 `compressedBoundWrapper` 样式，优化 `Select` 组件在大数据场景下的初始化性能

---

docs/markdown/shineout/changelog-common.md
package.json
packages/shineout-style/src/checkbox/checkbox.ts
packages/shineout-style/src/common/common.ts
packages/shineout-style/src/radio/radio.ts

feat: 更新版本号至 3.8.0-beta.10，优化 `Radio` 和 `Checkbox` 的选中动画效果

---

package.json
packages/hooks/src/utils/highlight.tsx
packages/shineout/src/select/__doc__/changelog.cn.md

24ce2282-874c-4360-9a04-5b2dd2364364

fix: 修复 `Select` 开启 `highlight` 后在 `renderItem` 中渲染非单层 dom 结构功能失效的问题

---

package.json
packages/base/src/table/table.tsx
packages/shineout/src/table/__doc__/changelog.cn.md

585ca8fa-b1dc-45dd-a4c6-b3396fdd114e

fix: 更新版本至 3.7.7-beta.6，修复 `Table` 组件在动态高度情况下，虚拟列表最后一条数据显示不全的问题

---

package.json
packages/base/src/table/table.tsx
packages/hooks/src/components/use-table/use-table-virtual.tsx
packages/shineout/src/table/__doc__/changelog.cn.md
packages/shineout/src/table/__example__/07-02-virtual-scroll.tsx

aeb0045f-70ec-4a8b-ba26-342f44f6dfa1

fix: 更新版本至 3.7.7-beta.7，修复 `Table` 组件的 `scrollToIndex` 方法滚动位置计算不准确的问题

---

packages/base/src/select/result-more.tsx
packages/shineout/src/cascader/__test__/__snapshots__/cascader.spec.tsx.snap
packages/shineout/src/select/__test__/__snapshots__/select.spec.tsx.snap
packages/shineout/src/tree-select/__test__/__snapshots__/treeSelect.spec.tsx.snap

从3.7.5-beta.9开始出现的
ad2b9681-770c-45d1-8399-ace4ea18074b

fix: 修复Select compressed初始化时第一项结果都不显示,而是显示more 的Tag

---

package.json
packages/shineout-style/src/version.ts
packages/shineout/src/index.ts

chore: release 3.7.7

---

package.json
packages/base/src/date-picker/date-picker.type.ts
packages/base/src/date-picker/day.tsx
packages/base/src/date-picker/time.tsx
packages/hooks/src/components/use-datepicker/use-time.tsx
packages/hooks/src/components/use-datepicker/use-time.type.ts
packages/shineout/src/date-picker/__doc__/changelog.cn.md

feat: `DatePicker` 增强 `disabledTime` 在开启 `range` 且为函数模式下的返回参数

---

package.json
packages/hooks/src/components/use-tree/use-tree.ts
packages/shineout/src/tree/__doc__/changelog.cn.md

fix: 修复 `Tree` 动态数据时，存在 children 为 undefined 导致报错的问题

---

package.json
packages/base/src/select/list-columns.tsx
packages/shineout-style/src/select/select.ts
packages/shineout/src/select/__doc__/changelog.cn.md

6998f07b-cf04-4614-91aa-7fcffc798219

chore: 更新版本至 3.7.8-beta.12，并修复 `Select` 组件在开启 `columns` 时的内边距样式问题

---

package.json
packages/base/src/table/table.tsx
packages/base/src/table/tbody.tsx
packages/base/src/table/tbody.type.ts
packages/base/src/table/tr.tsx
packages/hooks/src/components/use-table/use-table-virtual.tsx
packages/shineout/src/table/__doc__/changelog.cn.md

- 在 table.tsx 中添加 globalRowSelectMergeStartData 计算全局合并行信息
- 修复 tbody.tsx 中使用错误索引导致的 checkbox 状态丢失问题
- 在 tr.tsx 中确保 checkbox onChange 事件使用正确的合并行起始数据
- 解决了虚拟列表滚动时 checkbox 勾选状态丢失和位置跳动的问题
7cd69228-4fbb-4580-8e3d-2680ff226e3b

fix: 修复 Table 虚拟列表模式下合并行 checkbox 状态丢失的问题

---

packages/shineout-style/src/textarea/textarea.ts

eb74b366-1781-4600-9b18-ca837b144b1f

fix: 为 Textarea 组件添加最小高度样式，确保在不同内容情况下的显示一致性

---

package.json
packages/base/src/radio/group-context.ts
packages/base/src/radio/radio-group.tsx
packages/base/src/radio/simple-radio.tsx
packages/shineout-style/src/radio/radio.ts
packages/shineout/src/radio/__doc__/changelog.cn.md
packages/shineout/src/radio/__test__/__snapshots__/radio.spec.tsx.snap

10989904-0c25-4bdf-9969-2da9aaaf8341

fix: 修复 Radio.Group 在嵌套使用时，内层 Radio.Group 的勾选状态不符合预期的问题

---

package.json
packages/shineout-style/src/version.ts
packages/shineout/src/index.ts
packages/shineout/src/table/__doc__/changelog.cn.md

release: 🚀 3.7.9

---

package.json
packages/base/src/select/list-columns.tsx
packages/shineout/src/select/__doc__/changelog.cn.md

feat: 优化 `Select` 开启 `columns` 后，列表上方的`全选`字样支持多语言配置

---

package.json
packages/hooks/src/components/use-form/use-form-schema/form-schema-builder.ts
packages/shineout/src/form/__example__/test-001-base-form.tsx

fix: 修复 Form 的 getFormSchema 获取的json schema数据可能出现type为undefined的结构

---

package.json
packages/hooks/src/components/use-popup/use-popup.ts

refactor: 优化Popover defaultVisible, 使其优先级低于visible属性

---

docs/pages/markdown/index.tsx
docs/theme/layout/index.tsx

docs: 修正更新日志的version参数在hash query上的留存行为

---

packages/shineout/src/table/__example__/24-01-table-with-form.tsx
webpack/config.doc.js

docs: Table的可编辑行在编辑状态时,非编辑行的操作按钮设置为禁用状态

---

packages/base/src/card-group/item.tsx
packages/shineout/src/card-group/__example__/t-001-lazyout.tsx

perf: 再次优化CardGroup isInView监听逻辑

---

packages/shineout/src/table/__example__/24-01-table-with-form.tsx
packages/shineout/src/table/__example__/24-02-table-with-form.tsx

docs: 调整Table可以编辑行的示例交互

---

packages/shineout/src/select/__doc__/changelog.cn.md
packages/shineout/src/tooltip/__doc__/changelog.cn.md
packages/shineout/src/tree-select/__doc__/changelog.cn.md

docs: update changelog

---

package.json
packages/shineout-style/src/version.ts
packages/shineout/src/index.ts

chore: release 3.8.5
