- package.json
- packages/base/src/cascader/cascader.tsx
- packages/base/src/cascader/list.tsx
- packages/base/src/cascader/list.type.ts
- packages/base/src/cascader/node.tsx
- packages/hooks/src/components/use-cascader/use-cascader.ts
- packages/shineout-style/src/cascader/cascader.ts
- packages/shineout/src/cascader/__doc__/changelog.cn.md
- Cascader 设置 height 后会内容会溢出无法内滚，并且 minHeight 写死 导致 height 不生效
- Cascader 设置childrenKey 以后 renderItem 展示错误
- Cascader mode = 4 的时候 禁用节点需要点击可展开
> fix: 修复 cascader bug

- packages/base/src/checkbox/checkbox-group.tsx
| Browser   | * |
| Version   | * |
| OS       | * |
`Checkbox.Group` 在设置 `size` 属性后无法生效
- 修复 `Checkbox.Group` 设置 `size` 属性不生效的问题
> fix: 修复 Checkbox.Group size 属性失效的问题

- packages/base/src/table/table.type.ts
- packages/shineout/src/table/__doc__/changelog.cn.md
| Browser   | * |
| Version   | * |
| OS       | * |
`Table` 组件 `height` 属性输入字符串类型数据时 ts 报错
- 修复 `Table` 组件 `height` 类型错误的问题，支持 string 类型
> fix: 修复 Table 组件 height 类型错误的问题，支持 string 类型

- packages/base/src/spin/spin.tsx
- packages/base/src/spin/spin.type.ts
- packages/base/src/spin/spins.tsx
- packages/shineout/src/spin/__doc__/changelog.cn.md
- packages/shineout/src/spin/__test__/spin.spec.tsx
- packages/shineout/src/transfer/__test__/__snapshots__/transfer.spec.tsx.snap
| Browser   | * |
| Version   | * |
| OS       | * |
`Spin` 在设置 `className` 后样式会穿透传递至内部结构上出现多次消费的情况
- 修复 `Spin` 样式穿透生效的问题
> fix: 修复 Spin 样式穿透生效的问题

- package.json
- packages/base/src/checkbox/simple-checkbox.tsx
- packages/base/src/transfer/transfer.tsx
- packages/base/src/transfer/transfer.type.ts
- packages/shineout-style/src/transfer/transfer.ts
- packages/shineout/src/card-group/__test__/__snapshots__/cardGroup.spec.tsx.snap
- packages/shineout/src/checkbox/__test__/__snapshots__/checkbox.spec.tsx.snap
- packages/shineout/src/checkbox/__test__/__snapshots__/checkboxGroup.spec.tsx.snap
- packages/shineout/src/collapse/__test__/__snapshots__/collapse.spec.tsx.snap
- packages/shineout/src/drawer/__test__/__snapshots__/drawer.spec.tsx.snap
- packages/shineout/src/transfer/__doc__/changelog.cn.md
- packages/shineout/src/transfer/__test__/__snapshots__/transfer.spec.tsx.snap
- 新增 `equalPanelWidth` 属性，支持根据容器宽度均等分配面板宽度
- 优化勾选项的容器宽度，默认占满整行，超出后自动省略文案内容
> feat: Transfer 新增 equalPanelWidth 属性

- docs/markdown/shineout/changelog-v3.md
- packages/shineout-style/src/table/table.ts
> fix-table-column-shadow/main

- package.json
- packages/hooks/src/components/use-table/use-table-virtual.tsx
- packages/shineout/src/table/__example__/test-006-fix-scroll-y2.tsx
- `Table`合并行数据中有较大合并行数据时滚动出现空白的问题
> fix: `Table`合并行数据中有较大合并行数据时滚动出现空白的问题

- packages/base/src/virtual-scroll/scroll.tsx
修复 Table 虚拟滚动内部元素 scrollIntoView 会导致页面偏移的问题
> fix: 修复 table 虚拟滚动 内部 元素 scrollIntoView 会导致页面偏移的问题

- package.json
- packages/base/src/checkbox/checkbox-group.tsx
- packages/shineout/src/checkbox/__doc__/changelog.cn.md
- packages/shineout/src/checkbox/__example__/test-001-group-onchange.tsx
- 修复 `Checkbox.Group` 的children中的 `Checkbox` 的onChange不触发的问题
> fix: 修复 `Checkbox.Group` 的children中的 `Checkbox` 的onChange不触发的问题

- packages/base/src/date-picker/date-picker.tsx
- packages/base/src/date-picker/day.tsx
- packages/base/src/date-picker/day.type.ts
- packages/base/src/date-picker/picker.tsx
- packages/base/src/date-picker/picker.type.ts
- packages/hooks/src/components/use-datepicker/use-date.ts
- packages/hooks/src/components/use-datepicker/use-date.type.ts
- `DatePicker`的范围选择模式交互优化: 选择两个值后才关闭选择面板
> feat: `DatePicker`的范围选择模式交互优化: 选择两个值后才关闭选择面板

- package.json
- packages/hooks/src/components/use-table/use-table-virtual.tsx
- packages/shineout/src/table/__doc__/changelog.cn.md
- 修复TableRef的`scrollToIndex`的回调方法不生效问题
> fix: 修复`Table`的scrollToIndex的回调方法

- package.json
- packages/base/src/tree/tree.tsx
- packages/base/src/tree/tree.type.ts
- packages/shineout/src/tree/__doc__/changelog.cn.md
- packages/shineout/src/tree/__example__/11-highlight-control.tsx
- packages/shineout/src/tree/__test__/__snapshots__/tree.spec.tsx.snap
- packages/shineout/src/tree/__test__/tree.spec.tsx
- `Tree` 组件新增`setActive`，与`active`组成高亮的受控功能
> feat: `Tree` 组件新增`setActive`，与`active`组成高亮的受控功能

- package.json
- packages/base/src/select/list.tsx
- packages/base/src/select/select.type.ts
- packages/shineout-style/src/select/select.ts
- packages/shineout/src/select/__doc__/changelog.cn.md
- 修复 `Select` 开启absolute和multiple之后，下拉框较长选项的文字与勾选图标重叠的问题
> fix: 修复 `Select` 开启absolute和multiple之后，下拉框较长选项的文字与勾选图标重叠的问题

- package.json
- packages/hooks/src/components/use-form/use-form-control/use-form-control.ts
- packages/shineout/src/form/__doc__/changelog.cn.md
- 修复 Form.Field defaultValue 在部分场景下失效的问题
Form.Field 的 name 为数组，比如 ["a","b"]，defaultValue 为数组，且只有一个初始值，比如 [{name:'xxx',title:'xxx'}]。接口来的数据里不包含 a b 字段，比如 setValue({c:'xxx'})， 导致 defaultValue 不生效
> fix: 修复 Form.Field defaultValue 在部分场景下失效的问题

- package.json
- packages/base/src/card-group/item.tsx
- packages/base/src/card-group/lazyload.tsx
> perf: CardGroup refactor

- package.json
- packages/base/src/cascader/cascader.tsx
- packages/base/src/cascader/cascader.type.ts
- packages/base/src/cascader/filter-list.tsx
- packages/base/src/cascader/filter-list.type.ts
- packages/shineout-style/src/cascader/cascader.ts
- packages/shineout/src/cascader/__doc__/changelog.cn.md
- 修复 `Cascader` 非虚拟列表情况下搜索内容溢出列表的问题
- `Cascader` 单选模式下搜索结果列表支持虚拟列表
> fix: 修复 `Cascader`非虚拟列表情况下搜索内容溢出列表的问题，搜索结果列表支持虚拟列表

- package.json
- packages/base/src/select/result.tsx
- packages/base/src/select/result.type.ts
- packages/base/src/select/select.tsx
- packages/hooks/src/components/use-tree/use-tree.ts
- packages/hooks/src/components/use-tree/use-tree.type.ts
- packages/shineout/src/cascader/__doc__/changelog.cn.md
- 修复 `Cascader` 在开启 `unmatch` 情况下指定 renderItem 为 string 类型时渲染异常的问题
> fix: 修复 `Cascader` 在开启 `unmatch` 情况下指定 renderItem 为 string 类型时渲染异常的问题

- packages/base/src/tabs/tabs-panel.tsx
- Tabs动态设置disabled时的禁用不生效问题(Regression since 3.5.3)
> fix: Tabs动态设置disabled时的禁用不生效问题(Regression since 3.5.3)

- package.json
- packages/base/src/date-picker/day.tsx
- packages/shineout/src/date-picker/__doc__/changelog.cn.md
从远程获取的国际化资源包内的startOfWeek配置不是number类型时，星期顺序会错乱的问题
- 修复 `DatePicker` 从 setLocale获取到的 `startOfWeek` 是字符串时，得到星期顺序不正确的问题
> fix: 修复 `DatePicker` 从 setLocale获取到的 `startOfWeek` 是字符串时，得到星期顺序不正确的问题

- package.json
- packages/base/src/form/form-fieldset.tsx
- packages/shineout/src/form/__doc__/changelog.cn.md
> fix: 修复 `Form.FieldSet` 在非结尾位置插入数据时，数组的渲染显示异常的问题(Regression: v3.5.4)

- packages/base/src/radio/radio-group.tsx
- packages/shineout/src/radio/__doc__/changelog.cn.md
eaa4aef5-19b2-4a9b-9dce-8e97cebbb36a
> fix: 修复`Radio.Group` 传data属性用法下，设置 `size` 属性不生效的问题

- package.json
- packages/hooks/src/components/use-form/use-form.ts
- packages/shineout/src/form/__doc__/changelog.cn.md
- packages/shineout/src/form/__example__/test-004-deley-0.tsx
… since v3.4.4)
3c66ee32-1e20-485b-b088-dd057e8d0c43
> fix: 修复 `Form.Field` 下的Input使用onChange设置对象格式的值时，光标跳到末尾的问题(Regression:3.4.4

- package.json
- packages/base/src/cascader/cascader.tsx
- packages/shineout/src/cascader/__doc__/changelog.cn.md
- packages/shineout/src/date-picker/__test__/datePicker.spec.tsx
- 修复 `Cascader` 选择结果后箭头和关闭 icon 展示异常的问题
fa6c7efe-4fa9-44b1-af80-cb2715e1f99a
> fix: 修复 `Cascader` 选择结果后箭头和关闭 icon 展示异常的问题

- package.json
- packages/base/src/cascader/filter-node.tsx
- packages/base/src/cascader/filter-node.type.ts
- packages/shineout/src/cascader/__doc__/changelog.cn.md
- 修复 `Cascader` 在输入搜索过程中点击选项后 `onChange` 第二参数未返回的问题
aae6952c-d6a2-40b9-9717-e021b7de34de
> fix: 修复 `Cascader` 在输入搜索过程中点击选项后 `onChange` 第二参数未返回的问题

- package.json
- packages/shineout-style/src/popover/popover.ts
- packages/shineout/src/popover/__doc__/changelog.cn.md
- 修复 `Popover` 组件在 `position='left'` 模式下三角箭头和 trigger 元素之间的垫片元素不生效的问题
65d9ed78-1686-4eef-bceb-af687c5b5e88
> fix: 修复 `Popover` 组件在 `position='left'` 模式下三角箭头和 trigger 元素之间的垫片元素不生效的问题

- package.json
- packages/base/src/form/form-footer-context.tsx
- packages/base/src/form/form.tsx
- packages/shineout/src/form/__doc__/changelog.cn.md
- packages/shineout/src/form/__example__/test-005-base-form.tsx
> fix: `Form` 在 `Modal` 组件中嵌套使用时，子Form卸载后父Form无法提交的问题

- package.json
- packages/base/src/input/input.tsx
- packages/hooks/src/components/use-input/use-input-format.ts
- packages/shineout/src/input/__doc__/changelog.cn.md
- packages/shineout/src/input/__test__/input.spec.tsx
- 优化 `Input` 在 `type='number'` 开启 `coin` 下输入溢出内容时的交互逻辑
- 修复 `Input` 开启 `coin` 情况下初始化数据不展示千分号的问题
d5753719-5a18-4132-ad62-65e23d6a54ac
> feat/fix: 优化 `Input` 在 `type='number'` 开启 `coin` 下输入溢出内容时的交互逻辑、修复 `Input` 开启 `coin` 情况下初始化数据不展示千分号的问题

- package.json
- packages/base/src/checkbox/checkbox.tsx
- packages/base/src/list/list.tsx
- packages/shineout/src/checkbox/__doc__/changelog.cn.md
- packages/shineout/src/list/__doc__/changelog.cn.md
- 修复 `Checkbox` 触发两次 `onChange` 的问题
- 修复 `List` 组件设置 `size` 属性后选择行的 Checkbox 组件不跟随尺寸的问题
2708265f-20f2-4535-88ad-fd3d04ae3941
> fix: 修复 `Checkbox` 触发两次 `onChange` 和 `List` 设置尺寸后 Checkbox 尺寸不跟随的问题

- package.json
- packages/hooks/src/components/use-input/use-input-format.ts
- packages/shineout/src/input/__doc__/changelog.cn.md
948553d3-178b-45df-b663-a46d53c6e7b6
> fix: 修复 `Input` 开启 `digits` 是值为 0 的情况下依然可以输入小数的问题

- packages/base/src/progress/circle.tsx
- packages/base/src/transfer/transfer-list.tsx
- packages/shineout/src/transfer/__doc__/changelog.cn.md
d321839d-6d07-4023-adc3-540ff4f1be0d
> fix: 修复 `Transfer` 设置了 `renderFilter` 之后可能导致左右面板高度不一致的问题

- package.json
- packages/base/src/pagination/pagination-jumper.tsx
- packages/base/src/pagination/pagination-jumper.type.ts
- packages/base/src/pagination/pagination-simple.tsx
- packages/base/src/pagination/pagination.tsx
- packages/shineout/src/pagination/__doc__/changelog.cn.md
- packages/shineout/src/pagination/__test__/__snapshots__/pagination.spec.tsx.snap
- 修复 `Pagination` 的 `simple` 模式输入框不展示当前页的问题（Regression： since v3.6.0）
d3601609-7b6a-4e36-aa3d-0bb766b52eca
> fix: 修复 `Pagination` 的 `simple` 模式输入框不展示当前页的问题（Regression： since v3.6.0）

- packages/hooks/src/common/use-position-style/check-position.ts
- packages/hooks/src/common/use-position-style/index.ts
- packages/shineout/src/pagination/__doc__/changelog.cn.md
> feat: Popover类弹出层的父元素滚动超出视口时, 自动隐藏Popover

- packages/base/src/input/input-group.tsx
- packages/shineout/src/input/__doc__/changelog.cn.md
> fix: 修复 `Input.Group` 下面的 `Input` 的 `onBlur` 和 `onFocus` 回调函数的参数格式不正确的问题

- package.json
- packages/base/src/card/card.tsx
- packages/shineout/src/card/__doc__/changelog.cn.md
> fix: 修复 `Card.Header` 和 `Card.Footer` 在未开启 `moveable` 属性时不可选中文本的问题

- packages/hooks/src/components/use-form/use-form-control/use-form-control.ts
6f86a38d-fabc-4e85-80e1-25c4326017fe
> fix: 修复 `Form.Field` 在 `name` 为数组情况下组件卸载时错误信息无法清空的问题

- package.json
- packages/base/src/modal/modal-content.tsx
- packages/shineout/src/modal/__doc__/changelog.cn.md
f4c81797-ff66-471c-ac01-2fc2e6fb8d40
> fix: 修复 `Modal` 多层嵌套使用时，关闭子Modal但未关闭父Modal时body的滚动条出现的问题

- package.json
- packages/base/src/popover/popover.tsx
- packages/base/src/tooltip/tooltip.tsx
- packages/hooks/src/common/use-position-style/index.ts
- packages/shineout/src/popover/__doc__/changelog.cn.md
- packages/shineout/src/tooltip/__doc__/changelog.cn.md
> fix: 优化 Popover 和 Tooltip 在窗口resize和父容器滚动后依然能跟随目标

- packages/hooks/src/components/use-form/use-form-control/use-form-control.ts
- packages/hooks/src/components/use-form/use-form-control/use-form-control.type.ts
- packages/hooks/src/components/use-form/use-form.ts
- packages/shineout/src/form/__doc__/changelog.cn.md
f88e0d6d-c5db-4a36-af4f-2bfd008a4f4d
现象是：key 变了，组件卸载再挂载，value 没有变。理论上没给 reserveAble 的话，应该 value 会被删掉，然后用 defaultValue 替代
预期是：key 变了，组件先卸载，由于没给 reserveAble 会导致 value 被删了。但是马上又挂载了，由于没有 value ，所以 defaultValue 会上位，然后触发一次 onChange
组件 key 变化后触发了 unbind 和 bind，在 unbind 过程中会删除原字段，这个删除行为是在宏任务中完成的，这样执行顺序就变成了 unbind -> bind -> remove。由于组件带 defaultValue，在 bind 过程中会触发 onChange 以同步外部 value，因此总执行顺序为：unbind -> bind -> onChange -> remove 
然而，bind 过程中会去检查当前 value 中字段是否存在值，由于此时此刻还没有走到 remove 阶段，值依然存在于 value 中，所以并未走到是否让 defaultValue 上位替代的逻辑，从而引发了上述现象
> fix: 修复 `Form` 在表单组件的 key 变更后 `defaultValue` 无法设置成功的问题

- packages/shineout-style/src/tree-select/tree-select.ts
> chore: 调整 `TreeSelect` 的 `compressed` 展开弹出层最大宽高

- packages/base/src/popover/popover.tsx
- packages/base/src/tooltip/tooltip.tsx
- packages/hooks/src/common/use-position-style/check-element-size.ts
- packages/hooks/src/common/use-position-style/index.ts
- packages/shineout/src/tree-select/__doc__/changelog.cn.md
0eaba21f-425c-432f-bca4-21c1c22ff267
> fix: 修复 `TreeSelect` 在页面边界搜索时，下拉弹出层的位置未实时更新导致偏离父元素的问题

- package.json
- packages/base/src/form/form-flow.tsx
还是保持 strict 默认值，作为一个新特性存在。目前已经有用户依赖不开 strict 的行为
> fix: 调整 Form.Flow `strict` 属性 默认值

- package.json
- packages/base/src/transfer/transfer-list.type.ts
- packages/base/src/transfer/transfer.tsx
- packages/base/src/transfer/transfer.type.ts
- packages/shineout/src/transfer/__doc__/changelog.cn.md
7d8a6132-2f3d-4fb3-af7f-e21e30644168
> fix: 修复 `Transfer` 自定义children时左右勾选互斥的问题，并修正children的 `onSelect` ts类型

- package.json
- packages/shineout-style/src/cascader/cascader.ts
- packages/shineout-style/src/select/select.ts
- packages/shineout-style/src/tree-select/tree-select.ts
- packages/shineout/src/cascader/__doc__/changelog.cn.md
- packages/shineout/src/select/__doc__/changelog.cn.md
- packages/shineout/src/tree-select/__doc__/changelog.cn.md
40ffa19f-379b-492f-902b-fff3aafe4a3d
给 soui-result 这一层加了 100% 高度。场景是一个三层的 flex 嵌套，中间一层不给 height 100% 无法跟随子元素撑开的高度
> fix: 修复 `Select`、`TreeSelect`、`Cascader` 结果框高度不继承的问题

- package.json
- packages/shineout-style/src/button/button.ts
- packages/shineout/src/button/__doc__/changelog.cn.md
> fix: 修复 `Button` 在React 18以下初始化时有过渡动画的问题

- package.json
- packages/base/src/tree/tree.tsx
- packages/hooks/src/components/use-tree/use-tree.ts
- packages/hooks/src/components/use-tree/use-tree.type.ts
- packages/shineout/src/tree/__doc__/changelog.cn.md
783f3f69-7011-4b18-b4ac-c968c38bdf22
老版本 data 变了后 node 节点挂载的时候是直接从 props.expanded || props.defaultExpanded 里取值去判断是不是要展开节点
v3 在 useTree 里把这个属性做成受控了，所以 defaultExpanded 一开始如果没有值，后续有值的话是不会生效的，例子里的场景虽然 data 变了，但是 defaultExpanded 是根据 data 来实时改变的，理论上来说不应该生效，但是为了对齐表现，还是在 data 变了后，做一下展开检查行为，把 expanded 同步更新给了内部的状态
按照这次的方案修改，带来的一个影响就是，会额外触发一次 onExpand ，在外部可以打 log 看到，符合目前组件里大部分 defaultValue 的现象
> fix: 修复 `Tree` 在 data 发生变化后 `defaultExpanded` 不生效的问题

- package.json
- packages/hooks/src/components/use-tree/use-tree.ts
- packages/shineout/src/tree/__doc__/changelog.cn.md
60adac20-df43-477a-b9fa-304cb2e576c6
useEffect 死循环了，监听了一个一直被新创建的空数组，改成 props.data
> fix: 修复 `Tree` 在开启虚拟列表后 `data` 为 undefined 时可能存在死循环的问题

- package.json
- packages/base/src/modal/modal-content.tsx
- packages/shineout/src/modal/__doc__/changelog.cn.md
e696c587-114c-4fb8-974e-02ecc0c4b15a
> fix: 修复 `Modal` 组件在被外部卸载后无法重置 HTML 元素样式的问题

- package.json
- packages/base/src/tree-select/tree-select.tsx
- packages/base/src/upload/button.tsx
- packages/base/src/upload/button.type.ts
- packages/shineout/src/tree-select/__doc__/changelog.cn.md
死循环是因为 props 里的默认值直接给了 data=[] 引用疯狂刷新导致的
Upload.Button 新版本去掉了，老版本生效的，但是表现很诡异。用户使用了，所以对齐下诡异的表现
> fix: 修复 TreeSelect 开启 virtual 后传入 undefined 数据导致死循环问题、Upload.Button 传入 drop 属性失效的问题

- package.json
- packages/hooks/src/components/use-form/use-form.ts
- packages/shineout/src/form/__doc__/changelog.cn.md
- 修复 `Form` 组件在开启 `scrollToError` 后，Input组件的 `onEnterPress` 事件不触发的问题
- 修复 `Form` 的scrollToError偶现的跳转不过去的问题
3122a030-76ac-4989-b74e-29fc150ab496
> fix: 更新版本号至 3.7.3-beta.3，修复 `Form` 组件在开启 `scrollToError` 后，Input组件的 `onEnterPress` 事件不触发的问题

- package.json
- packages/base/src/input/simple-input.tsx
- packages/hooks/src/components/use-form/use-form.ts
- packages/shineout/src/form/__doc__/changelog.cn.md
- packages/shineout/src/input/__doc__/changelog.cn.md
91cf0081-3eb1-4e63-89bb-90265c7394a6
> fix: 修复 `Input` 组件的 `onEnterPress` 事件在开启 `Form` 的`scrollToError` 后偶现无法触发的问题

- package.json
- packages/base/src/form/form-item.tsx
- packages/base/src/form/form-item.type.ts
- packages/shineout-style/src/form/form-item.ts
- packages/shineout/src/form/__doc__/changelog.cn.md
- 修复 Form.Item嵌套使用，父级设置required为true，子级设置为false不生效的问题
> fix: 更新版本号至 3.7.4-beta.8，修复 `Form.Item` 嵌套使用时，子级的 `required` 属性设置为 `false` 不生效的问题，并新增样式支持

- package.json
- packages/hooks/src/components/use-popup/use-popup.ts
- packages/shineout/src/modal/__doc__/changelog.cn.md
3e4a36d0-4693-428f-b804-146d342ad216
gpt 的解释是：
1. **React 把所有鼠标事件都“绑”在 document 上统一处理**  
当浏览器触发一次原生 mouseover / mouseout，React 会在 document 上收到，再把它转换成自己的 *SyntheticEvent*，然后沿 **React 组件树** 依次分发。  
这一套“事件委托”机制与真实的 DOM 位置无关，只和 **Fiber 组件层级** 有关。
2. **createRoot / Portal 渲染的元素虽然 DOM 在外面，但逻辑上仍是父组件的后代**  
你在子组件里调用 `createRoot(container).render(<Tooltip/>)`（或 `<Portal />`）时：  
• DOM 节点放到了 `body` 等任意位置；  
• 但生成的 Fiber 仍挂回 “触发 render 的那个子组件”——因此依旧在父组件的 React 子树里。  
结果就是：当指针从父组件“管辖”范围外移入这个 tooltip，React 认为**进入了父组件的子孙**，于是合成了 `onMouseEnter` 并调用了你的回调。  
React 官方文档也明确指出，`onMouseEnter` / `onMouseLeave` 在 React 中是 *会冒泡* …
> fix: 修复 `Dropdown` 组件在开启 `hover` 模式时鼠标移入非 dom 包含关系元素导致意外触发打开列表的问题

- package.json
- packages/hooks/src/components/use-form/use-form.ts
- packages/shineout/src/form/__doc__/changelog.cn.md
3328f0f9-3ca5-4ab7-83fd-3470a56e353a
> fix: 修复 `Form` 对 `onChange` 的返回值直接修改数据后再设置新 value 不生效的问题

- README-zh_CN.md
- README.md
- package.json
- packages/base/package.json
- packages/hooks/package.json
- packages/shineout/package.json
将React最低版本要求提升至16.14.0，主要是因为组件库采用了新的JSX Transform（runtime: 'automatic'），这允许组件文件无需显式导入React。但这个特性需要React 16.14.0+的运行时支持，否则在用户项目中会因为找不到React引用而报错。
> chore: 更新 README 文件中的 React 版本要求，从 16.8.0 升级至 16.14.0

- package.json
- packages/base/src/select/select.tsx
- packages/shineout/src/select/__doc__/changelog.cn.md
c1a27d6d-4660-40b3-b1c5-e221380ec8c3
老版本 onFilter 的时候输入空格会过滤掉，新版本会携带，同步表现
> fix: 修复 `Select` 过滤过程中受 `trim` 属性影响，表现与老版本不一致的问题

- package.json
- packages/hooks/src/common/use-position-style/index.ts
- packages/hooks/src/utils/dom/document.ts
- packages/shineout/src/pagination/__doc__/changelog.cn.md
> fix: 修复 `Pagination` 的 `select` 下拉框在限制了高度的html或body滚动容器中第一次点击不出现的问题

- package.json
- packages/base/src/form/form-fieldset.tsx
- packages/shineout/src/form/__doc__/changelog.cn.md
- 在 Form.FieldSet 的 children 渲染函数中使用 Proxy 包装 value 参数
- 确保用户在 onChange({...value}) 中能获取到包含当前输入的最新值
- 修复 v2 升级到 v3 时的向后兼容性问题
- 支持展开操作符 {...value} 获取实时表单数据
e6454d5f-de63-40f1-ba7a-641777f4b769
> fix: 修复 `Form.FieldSet` 的 children 函数用法的 value 参数在某些场景下获取不到最新值的问题

- package.json
- packages/shineout-style/src/message/message.ts
- packages/shineout/src/message/__doc__/changelog.cn.md
> fix: 修复 `Message` 在 bottom-left 和 bottom-right 位置手动关闭弹窗时可能出现动画闪一下的问题

- packages/shineout-style/src/upload/upload.ts
- packages/shineout/src/upload/__doc__/changelog.cn.md
> fix: 修复 `Upload` 上传结果的图标在Safari浏览器中不可见的问题
